import {useEffect,useState} from 'react';import {useNavigate} from 'react-router-dom';import {sb,upload,useData,useSettings,inr} from './lib';
const T=[['home','Dashboard'],['msg','Messages'],['cat','Categories'],['prod','Products'],['gal','Gallery'],['site','Site & About'],['book','Pre-bookings']];
const del=async(t,id,load)=>{if(confirm('Delete this?')){await sb.from(t).delete().eq('id',id);load()}};
export default function Admin(){const nav=useNavigate(),[ok,setOk]=useState(false),[tab,setTab]=useState('home');
useEffect(()=>{sb.auth.getUser().then(async({data})=>{const u=data.user;if(!u)return nav('/contact');const{data:a}=await sb.from('admins').select('user_id').eq('user_id',u.id);a?.length?setOk(true):nav('/contact')})},[]);
if(!ok)return <p className="p-20 text-center">Checking access…</p>;const V={home:Dash,msg:Msgs,cat:Cats,prod:Prods,gal:Gal,site:Site,book:Book}[tab];
return <div className="mx-auto max-w-6xl px-4 py-6"><div className="mb-6 flex flex-wrap items-center gap-2"><h1 className="mr-auto text-3xl">Admin</h1>{T.map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`rounded-full px-4 py-1.5 text-sm ${tab===k?'bg-navy text-white':'bg-white text-navy shadow'}`}>{l}</button>)}<button className="px-3 text-sm underline" onClick={async()=>{await sb.auth.signOut();nav('/')}}>Log out</button></div><V/></div>}
function Dash(){const[c,setC]=useState({});useEffect(()=>{(async()=>{const n=async(t,f)=>{let q=sb.from(t).select('*',{count:'exact',head:true});if(f)q=q.eq(...f);return(await q).count};setC({Products:await n('products'),'New messages':await n('messages',['is_read',false]),'New pre-bookings':await n('prebookings',['status','new'])})})()},[]);
return <div className="grid gap-4 md:grid-cols-3">{Object.entries(c).map(([k,v])=><div key={k} className="rounded-3xl bg-white p-6 text-center shadow"><div className="font-head text-5xl font-extrabold text-coral">{v??0}</div>{k}</div>)}</div>}
function Msgs(){const[l,load]=useData(()=>sb.from('messages').select('*').order('created_at',{ascending:false}));
return <div className="space-y-3">{(l||[]).map(m=><div key={m.id} className={`rounded-2xl bg-white p-4 shadow ${m.is_read?'':'border-l-4 border-coral'}`}><div className="flex flex-wrap gap-2"><b className="mr-auto">{m.name} · {m.phone}</b><span className="text-xs text-slate-500">{new Date(m.created_at).toLocaleString()}</span></div><p className="my-2">{m.message}</p><div className="flex gap-4 text-sm"><a className="text-skyb" href={`tel:${m.phone}`}>Call</a><a className="text-skyb" target="_blank" href={`https://wa.me/${m.phone.replace(/\D/g,'').replace(/^(\d{10})$/,'91$1')}`}>WhatsApp</a><button onClick={async()=>{await sb.from('messages').update({is_read:!m.is_read}).eq('id',m.id);load()}}>{m.is_read?'Mark unread':'Mark read'}</button><button className="text-red-600" onClick={()=>del('messages',m.id,load)}>Delete</button></div></div>)}{l?.length===0&&<p>No messages yet.</p>}</div>}
function Cats(){const[l,load]=useData(()=>sb.from('categories').select('*').order('sort')),[subs,loadS]=useData(()=>sb.from('subcategories').select('*')),[n,setN]=useState(''),[f,setF]=useState(),[sc,setSc]=useState(''),[sn,setSn]=useState('');
return <div><div className="mb-6 flex flex-wrap gap-2"><input className="inp !w-52" placeholder="New category" value={n} onChange={e=>setN(e.target.value)}/><input type="file" accept="image/*" onChange={e=>setF(e.target.files[0])}/><button className="btn" onClick={async()=>{if(!n)return;await sb.from('categories').insert({name:n,cover_url:f?await upload('shop-images',f):null});setN('');load()}}>Add category</button></div>
<div className="mb-6 flex flex-wrap gap-2"><select className="inp !w-44" value={sc} onChange={e=>setSc(e.target.value)}><option value="">Category</option>{(l||[]).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="inp !w-52" placeholder="New sub-category" value={sn} onChange={e=>setSn(e.target.value)}/><button className="btn" onClick={async()=>{if(!sc||!sn)return;await sb.from('subcategories').insert({category_id:sc,name:sn});setSn('');loadS()}}>Add sub-category</button></div>
{(l||[]).map(c=><div key={c.id} className="mb-3 rounded-2xl bg-white p-3 shadow"><div className="flex items-center gap-3">{c.cover_url&&<img src={c.cover_url} alt="" className="h-10 w-10 rounded object-cover"/>}<b className="mr-auto">{c.name}</b><button className="text-red-600" onClick={()=>del('categories',c.id,load)}>Delete</button></div><div className="mt-2 flex flex-wrap gap-2">{(subs||[]).filter(s=>s.category_id===c.id).map(s=><span key={s.id} className="rounded-full bg-sunny/40 px-3 text-sm">{s.name} <button onClick={()=>del('subcategories',s.id,loadS)}>×</button></span>)}</div></div>)}</div>}
const E={name:'',category_id:'',subcategory_id:'',fabric:'',sizes:'',colours:'',price:'',description:'',in_stock:true,featured:false,is_new:false,images:[]};
function Prods(){const[l,load]=useData(()=>sb.from('products').select('*').order('created_at',{ascending:false})),[cats]=useData(()=>sb.from('categories').select('*')),[subs]=useData(()=>sb.from('subcategories').select('*')),[f,setF]=useState(null),[busy,setB]=useState(false);const on=k=>e=>setF({...f,[k]:e.target.type==='checkbox'?e.target.checked:e.target.value});
const add=async e=>{setB(true);try{const u=await Promise.all([...e.target.files].map(x=>upload('shop-images',x)));setF({...f,images:[...f.images,...u]})}catch(x){alert(x.message)}setB(false)};
const list=s=>String(s).split(',').map(x=>x.trim()).filter(Boolean);
const save=async e=>{e.preventDefault();const{id,created_at,...r}=f;r.price=Number(r.price)||0;r.category_id=r.category_id||null;r.subcategory_id=r.subcategory_id||null;r.sizes=list(r.sizes);r.colours=list(r.colours);const{error}=id?await sb.from('products').update(r).eq('id',id):await sb.from('products').insert(r);if(error)return alert(error.message);setF(null);load()};
if(f)return <form onSubmit={save} className="max-w-xl space-y-3"><input required className="inp" placeholder="Dress name" value={f.name} onChange={on('name')}/><select required className="inp" value={f.category_id||''} onChange={on('category_id')}><option value="">Category</option>{(cats||[]).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="inp" value={f.subcategory_id||''} onChange={on('subcategory_id')}><option value="">Sub-category</option>{(subs||[]).filter(s=>s.category_id===f.category_id).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>
<input className="inp" placeholder="Fabric" value={f.fabric||''} onChange={on('fabric')}/><input className="inp" placeholder="Sizes (comma separated: S, M, L)" value={f.sizes} onChange={on('sizes')}/><input className="inp" placeholder="Colours (comma separated)" value={f.colours} onChange={on('colours')}/><input type="number" className="inp" placeholder="Price (₹)" value={f.price} onChange={on('price')}/><textarea className="inp" placeholder="Description" value={f.description||''} onChange={on('description')}/>
<div className="flex flex-wrap gap-4"><label><input type="checkbox" checked={f.in_stock} onChange={on('in_stock')}/> In stock</label><label><input type="checkbox" checked={f.featured} onChange={on('featured')}/> Featured</label><label><input type="checkbox" checked={f.is_new} onChange={on('is_new')}/> New arrival</label></div>
<div><input type="file" accept="image/*" multiple onChange={add}/>{busy&&<span> Uploading…</span>}<div className="mt-2 flex flex-wrap gap-2">{f.images.map((u,i)=><div key={u} className="relative"><img src={u} alt="" className="h-24 w-20 rounded-xl object-cover"/><button type="button" onClick={()=>setF({...f,images:f.images.filter(x=>x!==u)})} className="absolute right-0 top-0 rounded-full bg-white px-1.5">×</button>{i>0&&<button type="button" onClick={()=>setF({...f,images:[u,...f.images.filter(x=>x!==u)]})} className="absolute bottom-0 w-full bg-black/60 text-xs text-white">Make first</button>}</div>)}</div></div>
<div className="flex gap-2"><button className="btn">Save dress</button><button type="button" onClick={()=>setF(null)} className="px-4">Cancel</button></div></form>;
return <div><button className="btn mb-4" onClick={()=>setF(E)}>Add dress</button>{(l||[]).map(p=><div key={p.id} className="mb-2 flex items-center gap-3 rounded-2xl bg-white p-3 shadow"><img src={p.images?.[0]} alt="" className="h-14 w-11 rounded-lg object-cover"/><span className="mr-auto">{p.name} · {inr(p.price)}</span><button onClick={()=>setF({...p,sizes:(p.sizes||[]).join(', '),colours:(p.colours||[]).join(', ')})} className="text-skyb">Edit</button><button onClick={()=>del('products',p.id,load)} className="text-red-600">Delete</button></div>)}</div>}
function Gal(){const[l,load]=useData(()=>sb.from('gallery').select('*').order('created_at',{ascending:false})),[b,setB]=useState(false);
return <div><label className="btn inline-block cursor-pointer">{b?'Uploading…':'Upload photos'}<input type="file" accept="image/*" multiple hidden onChange={async e=>{setB(true);for(const x of e.target.files)await sb.from('gallery').insert({url:await upload('shop-images',x)});setB(false);load()}}/></label>
<div className="mt-4 grid grid-cols-3 gap-3 md:grid-cols-5">{(l||[]).map(g=><div key={g.id} className="relative"><img src={g.url} alt="" className="aspect-square w-full rounded-2xl object-cover"/><button onClick={()=>del('gallery',g.id,load)} className="absolute right-1 top-1 rounded-full bg-white px-2">×</button></div>)}</div></div>}
function Site(){const[s,load]=useSettings(),[v,setV]=useState({}),g=k=>v[k]??s[k]??'';const set=async(k,val)=>{await sb.from('settings').upsert({key:k,value:String(val)});load();setV({...v,[k]:undefined})};
return <div className="max-w-xl space-y-3"><h3 className="text-2xl">About page</h3><div className="flex items-center gap-3">{s.owner_photo&&<img src={s.owner_photo} alt="" className="h-20 w-20 rounded-full object-cover"/>}<input type="file" accept="image/*" onChange={async e=>set('owner_photo',await upload('shop-images',e.target.files[0]))}/></div>
{[['owner_name','Owner name'],['years','Years (e.g. 12+)']].map(([k,l])=><input key={k} className="inp" placeholder={l} value={g(k)} onChange={e=>setV({...v,[k]:e.target.value})}/>)}<textarea className="inp" placeholder="Shop story" value={g('story')} onChange={e=>setV({...v,story:e.target.value})}/>
<button className="btn" onClick={async()=>{for(const k of['owner_name','years','story'])await sb.from('settings').upsert({key:k,value:g(k)});load();alert('Saved')}}>Save about</button>
<h3 className="pt-4 text-2xl">Offers banner</h3><input className="inp" placeholder="Banner text" value={g('banner_text')} onChange={e=>setV({...v,banner_text:e.target.value})}/><label><input type="checkbox" checked={g('banner_on')==='true'} onChange={e=>set('banner_on',e.target.checked)}/> Show banner</label> <button className="btn ml-3" onClick={()=>set('banner_text',g('banner_text'))}>Save banner</button></div>}
function Book(){const[l,load]=useData(()=>sb.from('prebookings').select('*').order('created_at',{ascending:false})),[z,setZ]=useState();
return <div className="space-y-3">{(l||[]).map(b=><div key={b.id} className="flex flex-wrap gap-4 rounded-2xl bg-white p-4 shadow">{b.product_image_url&&<img src={b.product_image_url} alt="" className="h-28 w-20 rounded-xl object-cover"/>}<div className="flex max-w-[16rem] flex-wrap gap-1">{(b.reference_image_urls||[]).map(u=><img key={u} src={u} onClick={()=>setZ(u)} alt="Reference" className="h-14 w-14 cursor-zoom-in rounded-lg object-cover"/>)}</div>
<div className="min-w-48 flex-1 text-sm"><b className="text-base">{b.name}</b> · {b.product_name}{b.custom_category&&` (${b.custom_category}, budget ${b.budget||'-'})`}<br/>{b.phone} {b.email&&`· ${b.email}`}<br/>{b.city}<br/>Size {b.size||'-'} · {b.colour||'-'} · Qty {b.quantity}{b.preferred_date&&` · by ${b.preferred_date}`}<br/>{b.message}<br/><a className="text-skyb" href={`tel:${b.phone}`}>Call</a> · <a className="text-skyb" target="_blank" href={`https://wa.me/${b.phone.replace(/\D/g,'').replace(/^(\d{10})$/,'91$1')}`}>WhatsApp</a></div>
<select value={b.status} onChange={async e=>{await sb.from('prebookings').update({status:e.target.value}).eq('id',b.id);load()}} className="inp !w-36 self-start">{['new','contacted','confirmed','cancelled'].map(s=><option key={s}>{s}</option>)}</select></div>)}{l?.length===0&&<p>No pre-bookings yet.</p>}
{z&&<div onClick={()=>setZ()} className="fixed inset-0 z-50 grid cursor-zoom-out place-items-center bg-black/90 p-4"><img src={z} alt="" className="max-h-full max-w-full"/></div>}</div>}
