import {useEffect,useState} from 'react';import {Routes,Route,Link,NavLink,useLocation} from 'react-router-dom';import {AnimatePresence,motion} from 'framer-motion';
import {sb,device,Logo,WishCtx,useData,ADDRESS} from './lib';import {Home,Collections,CategoryPage,Detail,Wishlist,About,Gallery,Contact,Faq,PreBookPage} from './pages';import Admin from './Admin';
function Nav(){const[s,setS]=useState(false),[open,setOpen]=useState(false),[cats]=useData(()=>sb.from('categories').select('*').order('sort'));
useEffect(()=>{const f=()=>setS(scrollY>40);addEventListener('scroll',f);return()=>removeEventListener('scroll',f)},[]);
const L=({to,children})=><NavLink to={to} onClick={()=>setOpen(false)} className={({isActive})=>`hover:text-sunny ${isActive?'text-sunny':''}`}>{children}</NavLink>;
return <motion.header animate={{paddingBlock:s?6:14}} className="fixed inset-x-0 top-0 z-40 bg-navy/95 text-white shadow-lg backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-4">
<Link to="/" className="flex items-center gap-2"><Logo size={s?36:44}/><span className="font-head text-xl font-extrabold text-sunny">Shanmukha Readymades</span></Link>
<button className="text-2xl md:hidden" onClick={()=>setOpen(!open)} aria-label="Menu">☰</button>
<nav className={`${open?'flex':'hidden'} absolute left-0 top-full w-full flex-col gap-3 bg-navy p-5 md:static md:flex md:w-auto md:flex-row md:items-center md:gap-6 md:bg-transparent md:p-0`}>
<L to="/">Home</L><div className="group relative"><L to="/collections">Collections ▾</L><div className="invisible absolute left-0 top-full min-w-40 rounded-2xl bg-white p-2 text-navy opacity-0 shadow-xl transition group-hover:visible group-hover:opacity-100 max-md:visible max-md:static max-md:bg-transparent max-md:text-white max-md:opacity-100">
{(cats||[]).map(c=><Link key={c.id} to={`/collections/${c.id}`} onClick={()=>setOpen(false)} className="block rounded-xl px-3 py-1.5 hover:bg-sunny hover:text-navy">{c.name}</Link>)}</div></div>
<L to="/gallery">Gallery</L><L to="/about">About</L><L to="/faq">FAQ</L><L to="/contact">Contact</L><L to="/wishlist">♥</L><Link to="/prebook" onClick={()=>setOpen(false)} className="rounded-full bg-coral px-4 py-1.5 font-semibold">Pre-book</Link></nav></div></motion.header>}
export default function App(){const loc=useLocation(),[ids,setIds]=useState([]);
useEffect(()=>{sb.from('wishlists').select('product_id').eq('device_id',device()).then(r=>setIds((r.data||[]).map(x=>x.product_id)))},[]);
const toggle=async id=>{const has=ids.includes(id);setIds(has?ids.filter(x=>x!==id):[...ids,id]);const q=sb.from('wishlists');has?await q.delete().match({device_id:device(),product_id:id}):await q.insert({device_id:device(),product_id:id})};
return <WishCtx.Provider value={{ids,toggle}}><Nav/><AnimatePresence mode="wait"><motion.main key={loc.pathname} initial={{opacity:0,x:40}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-40}} transition={{duration:.3}} className="min-h-screen pt-20">
<Routes location={loc}><Route path="/" element={<Home/>}/><Route path="/collections" element={<Collections/>}/><Route path="/collections/:catId" element={<CategoryPage/>}/><Route path="/item/:id" element={<Detail/>}/><Route path="/wishlist" element={<Wishlist/>}/><Route path="/about" element={<About/>}/><Route path="/gallery" element={<Gallery/>}/><Route path="/contact" element={<Contact/>}/><Route path="/faq" element={<Faq/>}/><Route path="/prebook" element={<PreBookPage/>}/><Route path="/admin" element={<Admin/>}/></Routes></motion.main></AnimatePresence>
<footer className="mt-16 bg-navy text-white"><div className="wave"/><div className="mx-auto max-w-6xl p-8 text-center"><Logo size={56}/><p className="mt-2 font-head text-2xl text-sunny">Shanmukha Readymades</p><p className="mx-auto mt-2 max-w-md text-sm opacity-80">{ADDRESS}</p><p className="mt-4 text-xs opacity-60">© {new Date().getFullYear()} Shanmukha Readymades</p></div></footer></WishCtx.Provider>}
