import {useState} from 'react';import {Link,useParams,useNavigate} from 'react-router-dom';import {motion,AnimatePresence} from 'framer-motion';
import {sb,upload,useData,useSettings,useWish,useLongPress,useCart,Reveal,Counter,Logo,inr,ACCENT,PHONE,ADDRESS} from './lib';
const Heart=({id})=>{const{ids,toggle}=useWish(),on=ids.includes(id);return <motion.button whileTap={{scale:1.5}} onClick={e=>{e.preventDefault();toggle(id)}} aria-label="Wishlist" className={`absolute right-3 top-3 grid h-9 w-9 place-items-center rounded-full bg-white/90 text-lg shadow ${on?'text-coral':'text-slate-400'}`}>{on?'♥':'♡'}</motion.button>};
const Card=({p,i=0})=><motion.div initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:(i%4)*.08}} whileHover={{y:-8,rotate:-.6}}><Link to={`/item/${p.id}`} className="relative block overflow-hidden rounded-3xl bg-white shadow-md">
<div className="aspect-[3/4] overflow-hidden bg-sunny/20"><img loading="lazy" src={p.images?.[0]} alt={p.name} className="h-full w-full object-cover transition duration-700 hover:scale-110"/></div><Heart id={p.id}/>{p.is_new&&<span className="absolute left-3 top-3 rounded-full bg-mint px-3 text-xs font-bold text-navy">NEW</span>}
<div className="p-4"><h3 className="text-lg font-bold">{p.name}</h3><p className="font-semibold text-coral">{inr(p.price)}</p></div></Link></motion.div>;
const Grid=({list})=>!list?<p className="p-10 text-center">Loading…</p>:!list.length?<p className="p-10 text-center">Nothing here yet. Check back soon!</p>:<div className="grid grid-cols-2 gap-4 md:grid-cols-4">{list.map((p,i)=><Card key={p.id} p={p} i={i}/>)}</div>;
const Title=({children,sub})=><div className="py-10 text-center"><h1 className="text-3xl font-extrabold sm:text-4xl md:text-5xl">{children}</h1>{sub&&<p className="mt-2 text-slate-500">{sub}</p>}<div className="wave mx-auto mt-4 w-40 rounded"/></div>;
const CatTile=({c})=><Link to={`/collections/${c.id}`} className="group relative block aspect-[4/3] overflow-hidden rounded-3xl shadow-md" style={{background:ACCENT[c.name]||'#4DB6E8'}}>{c.cover_url&&<img loading="lazy" src={c.cover_url} alt={c.name} className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-110"/>}<div className="absolute inset-0 grid place-items-end bg-gradient-to-t from-black/60 to-transparent p-4"><span className="font-head text-xl font-extrabold text-white sm:text-3xl">{c.name}</span></div></Link>;
export function Home(){const[nw]=useData(()=>sb.from('products').select('*').eq('is_new',true).limit(8)),[cats]=useData(()=>sb.from('categories').select('*').order('sort')),[st]=useSettings(),name='Shanmukha Readymades'.split('');
return <>{st.banner_on==='true'&&<div className="bg-coral py-2 text-center text-sm font-semibold text-white">{st.banner_text}</div>}
<section className="relative grid min-h-[80svh] place-items-center overflow-hidden bg-gradient-to-br from-navy via-[#2d3d85] to-skyb px-4 text-center">
{[...Array(16)].map((_,i)=><motion.span key={i} className="absolute text-2xl" style={{left:`${(i*9+4)%100}%`,top:`${(i*17)%90}%`,color:['#FFC93C','#FF6B6B','#5ED3A8','#fff'][i%4]}} animate={{y:[0,-35,0],rotate:[0,180,360],opacity:[.3,1,.3]}} transition={{duration:4+i%4,repeat:Infinity,delay:i*.25}}>{['✦','👕','●','👗'][i%4]}</motion.span>)}
<div className="relative"><div className="mx-auto w-fit"><Logo size={110} draw/></div><h1 className="mt-4 text-4xl font-extrabold !text-sunny sm:text-6xl md:text-7xl">{name.map((c,i)=><motion.span key={i} className="inline-block" initial={{opacity:0,y:40,rotate:10}} animate={{opacity:1,y:0,rotate:0}} transition={{delay:1.2+i*.05}}>{c===' '?'\u00A0':c}</motion.span>)}</h1>
<motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:2.4}} className="mt-3 text-lg text-white">Kids · Boys · Men · Girls | Rayachoty</motion.p>
<motion.div initial={{opacity:0,scale:.8}} animate={{opacity:1,scale:1}} transition={{delay:2.7}} className="mt-8 flex flex-wrap justify-center gap-3"><Link to="/collections" className="btn !bg-sunny !text-navy">Shop collections</Link><Link to="/prebook" className="btn !bg-coral">Pre-book a dress</Link></motion.div></div></section>
<div className="overflow-hidden bg-sunny py-3 text-navy"><div className="mq flex w-max gap-10 font-head text-2xl font-bold">{[...Array(8)].map((_,i)=><span key={i}>{['👶 Kids','🧒 Boys','👔 Men','👗 Girls'][i%4]}</span>)}</div></div>
<section className="mx-auto max-w-6xl px-4"><Title>Shop by category</Title><div className="grid grid-cols-2 gap-4 md:grid-cols-4">{(cats||[]).map((c,i)=><Reveal key={c.id} d={i*.08}><CatTile c={c}/></Reveal>)}</div></section>
<section className="mx-auto max-w-6xl px-4"><Title sub="Fresh in the shop">New arrivals</Title><Grid list={nw}/></section>
<section className="mx-auto mt-14 grid max-w-6xl grid-cols-3 gap-4 px-4 text-center">{[[12,'+','Years of trust'],[5000,'+','Happy customers'],[1000,'+','Styles in store']].map(([n,s,l])=><Reveal key={l}><div className="rounded-3xl bg-white p-5 shadow"><div className="font-head text-2xl font-extrabold text-coral sm:text-4xl md:text-5xl"><Counter to={n} suffix={s}/></div><div className="text-sm">{l}</div></div></Reveal>)}</section>
<section className="mx-auto mt-14 max-w-4xl px-4"><Reveal><div className="rounded-3xl bg-navy p-8 text-center text-white"><h2 className="!text-sunny text-3xl">Need a dress in your size?</h2><p className="mt-2">Pre-book any dress, even one you don't see here. Upload photos and we will arrange it.</p><Link to="/prebook" className="btn mt-4 inline-block !bg-coral">Pre-book now</Link></div></Reveal></section></>}
export function Collections(){const[c]=useData(()=>sb.from('categories').select('*').order('sort'));return <div className="mx-auto max-w-6xl px-4"><Title sub="Pick a category">Collections</Title><div className="grid grid-cols-2 gap-4 md:grid-cols-4">{(c||[]).map((x,i)=><Reveal key={x.id} d={i*.08}><CatTile c={x}/></Reveal>)}</div></div>}
export function CategoryPage(){const{catId}=useParams(),[sub,setSub]=useState(''),[size,setSize]=useState(''),[max,setMax]=useState(''),[sort,setSort]=useState('new');
const[c]=useData(()=>sb.from('categories').select('*').eq('id',catId),[catId]),[subs]=useData(()=>sb.from('subcategories').select('*').eq('category_id',catId),[catId]),[l]=useData(()=>sb.from('products').select('*').eq('category_id',catId),[catId]);
let f=(l||[]).filter(p=>(!sub||p.subcategory_id===sub)&&(!size||p.sizes?.includes(size))&&(!max||p.price<=+max));if(sort==='lo')f.sort((a,b)=>a.price-b.price);if(sort==='hi')f.sort((a,b)=>b.price-a.price);
const sizes=[...new Set((l||[]).flatMap(p=>p.sizes||[]))];
return <div className="mx-auto max-w-6xl px-4"><Title>{c?.[0]?.name||'Collection'}</Title><div className="mb-4 flex flex-wrap gap-2">{[{id:'',name:'All'},...(subs||[])].map(s=><button key={s.id} onClick={()=>setSub(s.id)} className={`rounded-full px-4 py-1.5 text-sm font-semibold transition ${sub===s.id?'bg-navy text-white':'bg-white text-navy shadow'}`}>{s.name}</button>)}</div>
<div className="mb-6 flex flex-wrap gap-2"><select className="inp !w-auto" value={size} onChange={e=>setSize(e.target.value)}><option value="">All sizes</option>{sizes.map(s=><option key={s}>{s}</option>)}</select><input type="number" className="inp !w-40" placeholder="Max price ₹" value={max} onChange={e=>setMax(e.target.value)}/><select className="inp !w-auto" value={sort} onChange={e=>setSort(e.target.value)}><option value="new">Newest</option><option value="lo">Price: low to high</option><option value="hi">Price: high to low</option></select></div><Grid list={l&&f}/></div>}
export function Detail(){const{id}=useParams(),[r]=useData(()=>sb.from('products').select('*').eq('id',id),[id]),[i,setI]=useState(0),[zoom,setZ]=useState(false),[book,setBook]=useState(false),[sz,setSz]=useState(''),[cl,setCl]=useState(''),[added,setAdded]=useState(false),{addCart}=useCart(),p=r?.[0];
if(!r)return <p className="p-20 text-center">Loading…</p>;if(!p)return <p className="p-20 text-center">Item not found.</p>;const im=p.images||[];
return <div className="mx-auto grid max-w-6xl gap-8 px-4 py-8 md:grid-cols-2"><div><div className="relative overflow-hidden rounded-3xl bg-sunny/20"><AnimatePresence mode="wait"><motion.img key={i} src={im[i]} alt={p.name} onClick={()=>setZ(true)} drag="x" dragConstraints={{left:0,right:0}} onDragEnd={(_,o)=>{if(o.offset.x<-60)setI((i+1)%im.length);if(o.offset.x>60)setI((i-1+im.length)%im.length)}} initial={{opacity:0,scale:1.05}} animate={{opacity:1,scale:1}} exit={{opacity:0}} className="aspect-[3/4] w-full cursor-zoom-in object-cover"/></AnimatePresence><Heart id={p.id}/></div>
<div className="mt-3 flex gap-2 overflow-x-auto">{im.map((u,k)=><img key={k} src={u} onClick={()=>setI(k)} alt="" className={`h-20 w-16 cursor-pointer rounded-xl object-cover ring-2 ${k===i?'ring-coral':'opacity-70 ring-transparent'}`}/>)}</div></div>
<div><h1 className="text-2xl font-extrabold sm:text-4xl">{p.name}</h1><p className="mt-2 text-2xl font-bold text-coral sm:text-3xl">{inr(p.price)}</p><dl className="mt-4 space-y-2"><div>Fabric: {p.fabric||'-'}</div><div className="flex flex-wrap gap-2">Sizes: {(p.sizes||[]).map(s=><span key={s} className="rounded-full bg-skyb/20 px-3 text-sm">{s}</span>)}</div><div className="flex flex-wrap gap-2">Colours: {(p.colours||[]).map(s=><span key={s} className="rounded-full bg-mint/30 px-3 text-sm">{s}</span>)}</div><div>{p.in_stock?'✅ In stock':'⏳ Out of stock, pre-book to reserve'}</div></dl><p className="mt-4 text-slate-600">{p.description}</p><div className="mt-4 flex flex-wrap gap-2">{p.sizes?.length>0&&<select className="inp !w-auto" value={sz} onChange={e=>setSz(e.target.value)}><option value="">Select size</option>{p.sizes.map(x=><option key={x}>{x}</option>)}</select>}{p.colours?.length>0&&<select className="inp !w-auto" value={cl} onChange={e=>setCl(e.target.value)}><option value="">Select colour</option>{p.colours.map(x=><option key={x}>{x}</option>)}</select>}</div><div className="mt-4 flex flex-wrap gap-3"><button className="btn" onClick={()=>{if(p.sizes?.length&&!sz)return alert('Please select a size');addCart({id:p.id,name:p.name,image:p.images?.[0],price:p.price,size:sz,colour:cl});setAdded(true)}}>Add to cart 🛒</button><button className="btn !bg-coral" onClick={()=>setBook(true)}>Pre-book this dress</button></div>{added&&<p className="mt-3 font-semibold text-navy">Added to cart! <Link to="/cart" className="underline">View cart</Link></p>}</div>
<AnimatePresence>{zoom&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setZ(false)} className="fixed inset-0 z-50 grid cursor-zoom-out place-items-center bg-black/90 p-4"><img src={im[i]} alt={p.name} className="max-h-full max-w-full"/></motion.div>}{book&&<PreBook p={p} close={()=>setBook(false)}/>}</AnimatePresence></div>}
function PreBook({p,items,close}){const{clearCart}=useCart();const[f,setF]=useState({name:'',phone:'',email:'',city:'',size:'',colour:'',quantity:1,preferred_date:'',message:'',custom_category:'',budget:''}),[files,setFiles]=useState([]),[st,setSt]=useState('idle'),[err,setErr]=useState(''),[wa,setWa]=useState('');const on=k=>e=>setF({...f,[k]:e.target.value});
const go=async e=>{e.preventDefault();setSt('busy');try{const refs=await Promise.all(files.map(x=>upload('prebook-refs',x)));const{error}=await sb.from('prebookings').insert({...f,quantity:items?items.reduce((a,x)=>a+x.qty,0):(+f.quantity||1),items:items||[],preferred_date:f.preferred_date||null,product_id:p?.id||null,product_name:items?('Cart: '+items.length+' items'):(p?.name||'Custom dress request'),product_image_url:items?items[0]?.image:(p?.images?.[0]||null),reference_image_urls:refs});if(error)throw error;if(items)clearCart();const t=['*New pre-booking*',p?.images?.[0]&&('Dress photo: '+p.images[0]),...(items||[]).flatMap((x,k)=>[x.image&&('Photo '+(k+1)+': '+x.image),(k+1)+'. '+x.name+' | Size '+(x.size||'-')+' | '+(x.colour||'-')+' | x'+x.qty+' | '+location.origin+'/item/'+x.id]),...refs.map((x,k)=>'Reference photo '+(k+1)+': '+x),!items&&('Dress: '+(p?.name||'Custom request')),!items&&(p?'Link: '+location.origin+'/item/'+p.id:'Category: '+f.custom_category+', Budget: '+f.budget),'Name: '+f.name,'Phone: '+f.phone,'City: '+f.city,!items&&('Size: '+f.size+', Colour: '+f.colour+', Qty: '+f.quantity),f.message&&('Note: '+f.message)].filter(Boolean).join('\n');const url='https://api.whatsapp.com/send?phone='+PHONE+'&text='+encodeURIComponent(t);setWa(url);setSt('done');setTimeout(()=>{window.location.href=url},1500)}catch(x){setErr(x.message);setSt('idle')}};
return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 grid place-items-start overflow-y-auto bg-black/60 p-4 md:place-items-center"><motion.div initial={{y:60,scale:.95}} animate={{y:0,scale:1}} className="my-4 w-full max-w-md rounded-3xl bg-cream p-4 sm:p-6">
{st==='done'?<div className="py-8 text-center"><motion.div initial={{scale:0}} animate={{scale:1}} transition={{type:'spring'}} className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-mint text-4xl text-white">✓</motion.div><h2 className="mt-4 text-3xl">Pre-booking received!</h2><p className="mt-2">We will call you on {f.phone} to confirm.</p><a href={wa} className="btn mt-4 inline-block !bg-mint !text-navy">Open WhatsApp</a><br/><button className="btn mt-3" onClick={close}>Close</button></div>:
<form onSubmit={go} className="space-y-3">{items?<h2 className="text-2xl">Pre-book your cart ({items.length} items)</h2>:p?<div className="flex items-center gap-3"><img src={p.images?.[0]} alt="" className="h-16 w-12 rounded-lg object-cover"/><h2 className="text-2xl">Pre-book: {p.name}</h2></div>:<h2 className="text-2xl">Pre-book a dress you need</h2>}
{!p&&!items&&<><select required className="inp" value={f.custom_category} onChange={on('custom_category')}><option value="">Category</option>{['Kids','Boys','Men','Girls'].map(c=><option key={c}>{c}</option>)}</select><input className="inp" placeholder="Budget (₹)" value={f.budget} onChange={on('budget')}/></>}
<input required className="inp" placeholder="Your name" value={f.name} onChange={on('name')}/><input required type="tel" className="inp" placeholder="Phone number" value={f.phone} onChange={on('phone')}/><input type="email" className="inp" placeholder="Email (optional)" value={f.email} onChange={on('email')}/><input className="inp" placeholder="City / address" value={f.city} onChange={on('city')}/>
{!items&&<div className="grid grid-cols-3 gap-2"><input className="inp" placeholder="Size" value={f.size} onChange={on('size')}/><input className="inp" placeholder="Colour" value={f.colour} onChange={on('colour')}/><input type="number" min="1" className="inp" value={f.quantity} onChange={on('quantity')}/></div>}<input type="date" className="inp" value={f.preferred_date} onChange={on('preferred_date')}/><textarea className="inp" placeholder={p?'Message':'Describe the dress you need'} value={f.message} onChange={on('message')}/>
<label className="block text-sm">Reference photos (up to 5)<input type="file" accept="image/*" multiple className="mt-1 block" onChange={e=>setFiles([...e.target.files].slice(0,5))}/></label>{files.length>0&&<p className="text-xs">{files.length} photo(s) selected</p>}{err&&<p className="text-sm text-red-600">{err}</p>}
<div className="flex gap-2"><button disabled={st==='busy'} className="btn flex-1">{st==='busy'?'Sending…':'Send pre-booking'}</button><button type="button" onClick={close} className="px-4 text-navy">Cancel</button></div></form>}</motion.div></motion.div>}
export const PreBookPage=()=>{const n=useNavigate();return <PreBook close={()=>n(-1)}/>};
export function Wishlist(){const{ids}=useWish(),[l]=useData(()=>ids.length?sb.from('products').select('*').in('id',ids):Promise.resolve({data:[]}),[ids.join()]);return <div className="mx-auto max-w-6xl px-4"><Title sub="Items you saved">Your wishlist</Title><Grid list={l}/></div>}
export function About(){const[st]=useSettings();return <div className="mx-auto max-w-4xl px-4"><Title>About us</Title><Reveal><div className="flex flex-col items-center gap-6 rounded-3xl bg-white p-5 text-center shadow sm:p-8 md:flex-row md:text-left"><div className="h-40 w-40 shrink-0 sm:h-52 sm:w-52 overflow-hidden rounded-full border-4 border-sunny bg-skyb/20">{st.owner_photo?<img src={st.owner_photo} alt="Owner" className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-6xl">👤</div>}</div>
<div><h2 className="text-3xl font-extrabold">{st.owner_name||'Gundre Kishore Kumar Reddy'}</h2><p className="font-semibold text-coral">Owner · {st.years||'12+'} years in the clothing industry</p><p className="mt-3 text-slate-600">{st.story}</p></div></div></Reveal>
<div className="mt-8 grid gap-4 md:grid-cols-3">{[['Quality first','Fabrics we would dress our own family in.'],['Fair prices','Honest prices for every budget.'],['Personal service','Pre-book and we find your size.']].map(([a,b],i)=><Reveal key={a} d={i*.12}><div className="rounded-3xl bg-white p-6 text-center shadow"><h3 className="text-xl">{a}</h3><p className="mt-1 text-sm text-slate-600">{b}</p></div></Reveal>)}</div></div>}
export function Gallery(){const[g]=useData(()=>sb.from('gallery').select('*').order('created_at',{ascending:false})),[z,setZ]=useState();return <div className="mx-auto max-w-6xl px-4"><Title sub="A look at our shop and styles">Gallery</Title>{g&&!g.length&&<p className="text-center">Photos coming soon.</p>}<div className="columns-2 gap-3 sm:columns-3 lg:columns-4">{(g||[]).map((x,i)=><motion.img key={x.id} loading="lazy" src={x.url} alt="" onClick={()=>setZ(x.url)} initial={{opacity:0,scale:.9}} whileInView={{opacity:1,scale:1}} viewport={{once:true}} transition={{delay:(i%4)*.08}} whileHover={{scale:1.03}} className="mb-3 w-full cursor-zoom-in rounded-2xl"/>)}</div>
{z&&<div onClick={()=>setZ()} className="fixed inset-0 z-50 grid cursor-zoom-out place-items-center bg-black/90 p-4"><img src={z} alt="" className="max-h-full max-w-full"/></div>}</div>}
export function Faq(){const q=[['Can I pre-book a dress?','Yes. Use the Pre-book button on any dress, or the Pre-book page for a dress not listed.'],['Do you offer online payment?','No. Pre-book online and pay when you collect from the shop.'],['Can I exchange sizes?','Please ask in the shop; we will help you find the right fit.']];
return <div className="mx-auto max-w-3xl px-4"><Title>FAQ & size guide</Title>{q.map(([a,b])=><Reveal key={a}><details className="mb-3 rounded-2xl bg-white p-4 shadow"><summary className="cursor-pointer font-bold text-navy">{a}</summary><p className="mt-2 text-slate-600">{b}</p></details></Reveal>)}
<Reveal><div className="mt-8 overflow-x-auto rounded-3xl bg-white p-4 shadow"><table className="w-full text-center text-sm"><thead><tr className="text-navy"><th>Age</th><th>Size</th><th>Chest (in)</th></tr></thead><tbody>{[['1-2 yrs','S','20'],['3-4 yrs','M','22'],['5-6 yrs','L','24'],['7-8 yrs','XL','26'],['9-10 yrs','XXL','28']].map(r=><tr key={r[0]} className="border-t">{r.map(c=><td key={c} className="py-2">{c}</td>)}</tr>)}</tbody></table><p className="mt-2 text-xs text-slate-500">Approximate sizes. Please confirm in the shop.</p></div></Reveal></div>}
export function Contact(){const nav=useNavigate(),[login,setLogin]=useState(false),[m,setM]=useState({name:'',phone:'',message:''}),[st,setSt]=useState('idle'),lp=useLongPress(()=>setLogin(true));
const send=async e=>{e.preventDefault();setSt('busy');const{error}=await sb.from('messages').insert(m);setSt(error?'err':'done');if(!error)setM({name:'',phone:'',message:''})};
return <div className="mx-auto max-w-6xl px-4"><Title>Visit us</Title><div className="grid gap-8 md:grid-cols-2"><div className="space-y-3"><p className="text-lg">{ADDRESS}</p><p className="text-sm text-slate-500">Open daily, 10:00 AM to 9:00 PM</p><a className="btn inline-block" href={`tel:+${PHONE}`}>Call us</a> <a className="btn inline-block !bg-mint !text-navy" href={`https://wa.me/${PHONE}`}>WhatsApp</a>
{st==='done'?<motion.div initial={{scale:.8,opacity:0}} animate={{scale:1,opacity:1}} className="rounded-3xl bg-mint/30 p-6 text-center"><div className="text-4xl">✓</div><p className="font-bold">Message sent! We will get back to you.</p><button className="mt-2 underline" onClick={()=>setSt('idle')}>Send another</button></motion.div>:
<form className="space-y-3 pt-3" onSubmit={send}><input required className="inp" placeholder="Your name" value={m.name} onChange={e=>setM({...m,name:e.target.value})}/><input required type="tel" className="inp" placeholder="Phone number" value={m.phone} onChange={e=>setM({...m,phone:e.target.value})}/><textarea required className="inp" placeholder="Your message" value={m.message} onChange={e=>setM({...m,message:e.target.value})}/>{st==='err'&&<p className="text-sm text-red-600">Could not send. Please try again.</p>}<button className="btn select-none" disabled={st==='busy'} {...lp}>{st==='busy'?'Sending…':'Send message'}</button></form>}</div>
<iframe title="Map" loading="lazy" className="h-64 w-full rounded-3xl border-0 sm:h-96" src={`https://maps.google.com/maps?q=${encodeURIComponent(ADDRESS)}&output=embed`}/></div>{login&&<AdminLogin close={()=>setLogin(false)} ok={()=>nav('/admin')}/>}</div>}
function AdminLogin({close,ok}){const[e,setE]=useState(''),[p,setP]=useState(''),[er,setEr]=useState('');
const go=async x=>{x.preventDefault();const{data,error}=await sb.auth.signInWithPassword({email:e,password:p});if(error)return setEr(error.message);const{data:a}=await sb.from('admins').select('user_id').eq('user_id',data.user.id);if(!a?.length){await sb.auth.signOut();return setEr('This account is not an admin.')}ok()};
return <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><motion.form initial={{scale:.9,opacity:0}} animate={{scale:1,opacity:1}} onSubmit={go} className="w-full max-w-sm space-y-3 rounded-3xl bg-cream p-6"><h2 className="text-3xl">Admin login</h2><input required type="email" className="inp" placeholder="Email" value={e} onChange={x=>setE(x.target.value)}/><input required type="password" className="inp" placeholder="Password" value={p} onChange={x=>setP(x.target.value)}/>{er&&<p className="text-sm text-red-600">{er}</p>}<div className="flex gap-2"><button className="btn flex-1">Log in</button><button type="button" onClick={close} className="px-4 text-navy">Cancel</button></div></motion.form></div>}

export function CartPage(){const{cart,setQty}=useCart(),[book,setBook]=useState(null),total=cart.reduce((a,x)=>a+x.price*x.qty,0);
return <div className="mx-auto max-w-3xl px-4"><Title sub="Add dresses, then pre-book them together">Your cart</Title>
{!cart.length&&!book&&<p className="text-center">Your cart is empty. <Link to="/collections" className="underline">Browse collections</Link></p>}
<div className="space-y-3">{cart.map((x,i)=><div key={i} className="flex flex-wrap items-center gap-3 rounded-2xl bg-white p-3 shadow"><img src={x.image} alt="" className="h-20 w-16 rounded-xl object-cover"/><div className="mr-auto text-sm"><b className="text-base">{x.name}</b><br/>{x.size&&'Size '+x.size} {x.colour&&'· '+x.colour}<br/>{inr(x.price)}</div><div className="flex items-center gap-2"><button className="h-8 w-8 rounded-full bg-sunny font-bold" onClick={()=>setQty(i,x.qty-1)}>−</button>{x.qty}<button className="h-8 w-8 rounded-full bg-sunny font-bold" onClick={()=>setQty(i,x.qty+1)}>+</button></div><button className="text-red-600" aria-label="Remove" onClick={()=>setQty(i,0)}>✕</button></div>)}</div>
{cart.length>0&&<div className="mt-6 flex items-center justify-between rounded-2xl bg-navy p-4 text-white"><span>Total (pay at shop): <b className="text-sunny">{inr(total)}</b></span><button className="btn !bg-coral" onClick={()=>setBook(cart)}>Pre-book all</button></div>}
{book&&<PreBook items={book} close={()=>setBook(null)}/>}</div>}